### ISSUE TITLE
Error Loading Accessory

### ISSUE THREAD

**Issue by bryantcoles** [mkormendy/node-alarm-dot-com#3]
Any idea why I continue to get this error when launching Homebridge?

pi@raspberrypi:~ $ homebridge
[2018-9-4 19:50:41] Loaded config.json with 1 accessories and 1 platforms.
[2018-9-4 19:50:41] ---
[2018-9-4 19:50:41] Loaded plugin: homebridge-node-alarm-dot-com
[2018-9-4 19:50:41] Registering platform 'homebridge-node-alarm-dot-com.Alarmdotcom'
[2018-9-4 19:50:41] ---
[2018-9-4 19:50:41] Loading 1 platforms...
[2018-9-4 19:50:41] [Security System] Initializing Alarmdotcom platform...
[2018-9-4 19:50:41] Loading 1 accessories...
/usr/lib/node_modules/homebridge/lib/api.js:50
  if (name.indexOf('.') == -1) {
           ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:50:12)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:286:42)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:87:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by mkormendy** [comment]
What version of node are you running? what about the version of homebridge?

**Comment by bryantcoles** [comment]
node -v returns:
**v8.11.4**
npm -g outdated returns nothing.

**Comment by bryantcoles** [comment]
Got it working. Issue with my config file.
